version: "3.8"
services:
  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
  postgres:
    hostname: postgres
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=test
    ports:
      - "5432:5432"
    volumes:
      - ./sql/pg/init.sql:/docker-entrypoint-initdb.d/init.sql
